/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BackupService } from "../backup.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BackupCreateInput } from "./BackupCreateInput";
import { Backup } from "./Backup";
import { BackupFindManyArgs } from "./BackupFindManyArgs";
import { BackupWhereUniqueInput } from "./BackupWhereUniqueInput";
import { BackupUpdateInput } from "./BackupUpdateInput";
import { RestoreFindManyArgs } from "../../restore/base/RestoreFindManyArgs";
import { Restore } from "../../restore/base/Restore";
import { RestoreWhereUniqueInput } from "../../restore/base/RestoreWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BackupControllerBase {
  constructor(
    protected readonly service: BackupService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Backup })
  @nestAccessControl.UseRoles({
    resource: "Backup",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBackup(@common.Body() data: BackupCreateInput): Promise<Backup> {
    return await this.service.createBackup({
      data: data,
      select: {
        createdAt: true,
        fileCount: true,
        id: true,
        note: true,
        size: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Backup] })
  @ApiNestedQuery(BackupFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Backup",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async backups(@common.Req() request: Request): Promise<Backup[]> {
    const args = plainToClass(BackupFindManyArgs, request.query);
    return this.service.backups({
      ...args,
      select: {
        createdAt: true,
        fileCount: true,
        id: true,
        note: true,
        size: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Backup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Backup",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async backup(
    @common.Param() params: BackupWhereUniqueInput
  ): Promise<Backup | null> {
    const result = await this.service.backup({
      where: params,
      select: {
        createdAt: true,
        fileCount: true,
        id: true,
        note: true,
        size: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Backup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Backup",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBackup(
    @common.Param() params: BackupWhereUniqueInput,
    @common.Body() data: BackupUpdateInput
  ): Promise<Backup | null> {
    try {
      return await this.service.updateBackup({
        where: params,
        data: data,
        select: {
          createdAt: true,
          fileCount: true,
          id: true,
          note: true,
          size: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Backup })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Backup",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBackup(
    @common.Param() params: BackupWhereUniqueInput
  ): Promise<Backup | null> {
    try {
      return await this.service.deleteBackup({
        where: params,
        select: {
          createdAt: true,
          fileCount: true,
          id: true,
          note: true,
          size: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/restores")
  @ApiNestedQuery(RestoreFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Restore",
    action: "read",
    possession: "any",
  })
  async findRestores(
    @common.Req() request: Request,
    @common.Param() params: BackupWhereUniqueInput
  ): Promise<Restore[]> {
    const query = plainToClass(RestoreFindManyArgs, request.query);
    const results = await this.service.findRestores(params.id, {
      ...query,
      select: {
        backup: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        createdBy: {
          select: {
            id: true,
          },
        },

        details: true,
        id: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/restores")
  @nestAccessControl.UseRoles({
    resource: "Backup",
    action: "update",
    possession: "any",
  })
  async connectRestores(
    @common.Param() params: BackupWhereUniqueInput,
    @common.Body() body: RestoreWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      restores: {
        connect: body,
      },
    };
    await this.service.updateBackup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/restores")
  @nestAccessControl.UseRoles({
    resource: "Backup",
    action: "update",
    possession: "any",
  })
  async updateRestores(
    @common.Param() params: BackupWhereUniqueInput,
    @common.Body() body: RestoreWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      restores: {
        set: body,
      },
    };
    await this.service.updateBackup({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/restores")
  @nestAccessControl.UseRoles({
    resource: "Backup",
    action: "update",
    possession: "any",
  })
  async disconnectRestores(
    @common.Param() params: BackupWhereUniqueInput,
    @common.Body() body: RestoreWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      restores: {
        disconnect: body,
      },
    };
    await this.service.updateBackup({
      where: params,
      data,
      select: { id: true },
    });
  }
}
