/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EmailMapService } from "../emailMap.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EmailMapCreateInput } from "./EmailMapCreateInput";
import { EmailMap } from "./EmailMap";
import { EmailMapFindManyArgs } from "./EmailMapFindManyArgs";
import { EmailMapWhereUniqueInput } from "./EmailMapWhereUniqueInput";
import { EmailMapUpdateInput } from "./EmailMapUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EmailMapControllerBase {
  constructor(
    protected readonly service: EmailMapService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EmailMap })
  @nestAccessControl.UseRoles({
    resource: "EmailMap",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEmailMap(
    @common.Body() data: EmailMapCreateInput
  ): Promise<EmailMap> {
    return await this.service.createEmailMap({
      data: {
        ...data,

        organization: data.organization
          ? {
              connect: data.organization,
            }
          : undefined,
      },
      select: {
        box: true,
        createdAt: true,
        fullName: true,
        gDrive: true,
        id: true,
        oneDrive: true,

        organization: {
          select: {
            id: true,
          },
        },

        thumbNail: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [EmailMap] })
  @ApiNestedQuery(EmailMapFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "EmailMap",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async emailMaps(@common.Req() request: Request): Promise<EmailMap[]> {
    const args = plainToClass(EmailMapFindManyArgs, request.query);
    return this.service.emailMaps({
      ...args,
      select: {
        box: true,
        createdAt: true,
        fullName: true,
        gDrive: true,
        id: true,
        oneDrive: true,

        organization: {
          select: {
            id: true,
          },
        },

        thumbNail: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EmailMap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmailMap",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async emailMap(
    @common.Param() params: EmailMapWhereUniqueInput
  ): Promise<EmailMap | null> {
    const result = await this.service.emailMap({
      where: params,
      select: {
        box: true,
        createdAt: true,
        fullName: true,
        gDrive: true,
        id: true,
        oneDrive: true,

        organization: {
          select: {
            id: true,
          },
        },

        thumbNail: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EmailMap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmailMap",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEmailMap(
    @common.Param() params: EmailMapWhereUniqueInput,
    @common.Body() data: EmailMapUpdateInput
  ): Promise<EmailMap | null> {
    try {
      return await this.service.updateEmailMap({
        where: params,
        data: {
          ...data,

          organization: data.organization
            ? {
                connect: data.organization,
              }
            : undefined,
        },
        select: {
          box: true,
          createdAt: true,
          fullName: true,
          gDrive: true,
          id: true,
          oneDrive: true,

          organization: {
            select: {
              id: true,
            },
          },

          thumbNail: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EmailMap })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmailMap",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEmailMap(
    @common.Param() params: EmailMapWhereUniqueInput
  ): Promise<EmailMap | null> {
    try {
      return await this.service.deleteEmailMap({
        where: params,
        select: {
          box: true,
          createdAt: true,
          fullName: true,
          gDrive: true,
          id: true,
          oneDrive: true,

          organization: {
            select: {
              id: true,
            },
          },

          thumbNail: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
